name: "Setup and Build Step"
description: "Run steps to build project"
runs:
  using: "composite"
  steps:
    - name: Make Gradle Executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
