name: Android Artifact
run-name: Android Artifact execute by @${{ github.actor }}

on: [ workflow_dispatch ]

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/android_quality.yml
    secrets: inherit

  artifact:
    name: Artifact
    needs: [ quality ]
    uses: ./.github/workflows/android_qa_apk.yml
    secrets: inherit
