name: Android Deploy
run-name: Android Deploy execute by @${{ github.actor }}

on:
  push:
    branches:
      - 'develop'

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/android_quality.yml
    secrets: inherit

  artifact:
    name: Artifact
    needs: [ quality ]
    uses: ./.github/workflows/android_qa_apk.yml
    secrets: inherit
