name: Android Validation
run-name: Android Validation execute by @${{ github.actor }}

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/android_quality.yml
    secrets: inherit
