name: Android Publish
run-name: Android Publish execute by @${{ github.actor }}

on:
  push:
    branches:
      - 'master'

jobs:
  quality:
    name: Quality
    uses: ./.github/workflows/android_quality.yml
    secrets: inherit

  publish:
    name: Publish
    needs: [ quality ]
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Setup Project
        uses: ./.github/actions/android

      - name: Set Local Properties
        uses: ./.github/actions/local-properties
        with:
          key-prod: ${{ secrets.LOCAL_PROPERTIES_KEY_PROD }}
          key-qa: ${{ secrets.LOCAL_PROPERTIES_KEY_QA }}

      - name: Signing App Release
        run: |
          ./gradlew app:bundleRelease
          ./gradlew app:assembleRelease

      - name: Upload Artifact APK Release
        uses: actions/upload-artifact@v7
        with:
          name: apk-release
          path: ./app/build/outputs/apk/release

      - name: Upload Artifact Bundle Release
        uses: actions/upload-artifact@v7
        with:
          name: apk-bundle-release
          path: ./app/build/outputs/bundle/release

      - name: Create Tag Release
        run: |
          versionFormatted=`grep '^app-version-name' ./gradle/libs.versions.toml | cut -d'"' -f2`
          echo "Version: $versionFormatted"
          git tag $versionFormatted
          git push origin --tags

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.1.5
        with:
          serviceAccountJsonPlainText: ${{ secrets.SIGNING_SERVICE_ACCOUNT }}
          packageName: com.hacybeyker.movieoh
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: alpha
