name: Android Validation
run-name: Android Validation execute by @${{ github.actor }}

on:
  pull_request:
    branches:
      - 'develop'

env:
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  LOCAL_PROPERTIES_KEY_PROD: ${{ secrets.LOCAL_PROPERTIES_KEY_PROD }}
  LOCAL_PROPERTIES_KEY_QA: ${{ secrets.LOCAL_PROPERTIES_KEY_QA }}

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true

      - name: Setup Project
        uses: ./.github/actions/android

      - name: SetLocal Properties
        run: |
          echo KEY_PROD=$LOCAL_PROPERTIES_KEY_PROD >> local.properties
          echo KEY_QA=$LOCAL_PROPERTIES_KEY_QA >> local.properties

      - name: Run Lint
        uses: ./.github/actions/lint

      - name: Upload Lint Test Report
        uses: actions/upload-artifact@v4
        with:
          name: lint_report
          path: app/build/reports/lint-results-debug.html

      - name: Upload Detekt Report
        uses: actions/upload-artifact@v4
        with:
          name: detekt_report
          path: app/build/reports/detekt

      - name: Run Tests
        run: ./gradlew app:testDebugUnitTest

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Run Jacoco Test Report
        run: ./gradlew app:jacocoTestReport

      - name: Upload Coverage Test Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco_test_report
          path: app/build/reports/jacoco/jacocoTestReport/

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew app:jacocoTestCoverageVerification

      - name: Run SonarQube Scan
        run: ./gradlew app:sonarqube -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.login=${{ secrets.SONARCLOUDTOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}